### ISSUE TITLE
Brush Sizes

### ISSUE THREAD

**Issue by bbbmmmlll** [notimetoplay/ascii-mapper#5]
Sometimes you want to carve out a two tile wide hall or make a wide river. Being able to have a larger brush would save time. It also doubles as an eraser.

**Comment by felixp7** [comment]
That would complicate things for little benefit, far as I can tell. How would it even work for areas just 2 tiles wide/high?

**Comment by bbbmmmlll** [comment]
I think of it as the brush size in a paint program. I would mainly use it clear or change large sections at a time. I don't have a strong use case, but I would use it to replace the dot symbols with blank spaces which is what I use for my maps. My workaround would be to edit the source and change the default or load a text file filled with spaces.

**Comment by felixp7** [comment]
Right. I was thinking to cover this use case with the fill tool, whenever I get around to it. In the mean time, might add an option to fill a new map with whatever character is currently selected.

**Comment by felixp7** [comment]
After some consideration, this is just too complicated and misses the point.
